"""Domain handler registry consumed by the single MCP catalog."""
from __future__ import annotations

from kreports.mcp.handlers.auditor import (
    handle_build_audit_acceptance_pack,
    handle_compare_peer_accounting_policies,
    handle_compare_peer_audit_fees,
    handle_compare_peer_audit_procedures,
    handle_compare_peer_audit_report_matters,
    handle_compare_peer_kam_topics,
    handle_compare_peer_risk_profile,
    handle_estimate_audit_hours_proxy,
    handle_get_accounting_policy,
    handle_get_accounting_policy_changes,
    handle_get_audit_history,
    handle_get_audit_report_sections,
    handle_get_kam_lifecycle,
    handle_get_subsidiary_auditors,
    handle_search_audit_procedures,
    handle_search_audit_report_matters,
)
from kreports.mcp.handlers.company import (
    handle_get_business_overview,
    handle_get_financial_snapshot,
    handle_get_semantic_company_context,
    handle_search_company,
)
from kreports.mcp.handlers.investor import (
    handle_build_dcf_model_pack,
    handle_detect_restatement,
    handle_get_dcf_input_candidates,
    handle_get_investor_signals,
    handle_get_quality_of_earnings_pack,
    handle_score_going_concern,
    handle_search_disclosure_events,
)
from kreports.mcp.handlers.search import (
    handle_compare_to_industry,
    handle_compare_to_industry_multi,
    handle_fetch_disclosure_on_demand,
    handle_get_industry_audit_landscape,
    handle_search_dataset,
    handle_select_peer_group,
)


HANDLERS = {
    "search_company": handle_search_company,
    "get_financial_snapshot": handle_get_financial_snapshot,
    "score_going_concern": handle_score_going_concern,
    "detect_restatement": handle_detect_restatement,
    "get_accounting_policy": handle_get_accounting_policy,
    "get_audit_history": handle_get_audit_history,
    "get_subsidiary_auditors": handle_get_subsidiary_auditors,
    "compare_to_industry": handle_compare_to_industry,
    "get_business_overview": handle_get_business_overview,
    "get_semantic_company_context": handle_get_semantic_company_context,
    "get_investor_signals": handle_get_investor_signals,
    "select_peer_group": handle_select_peer_group,
    "compare_to_industry_multi": handle_compare_to_industry_multi,
    "compare_peer_audit_fees": handle_compare_peer_audit_fees,
    "compare_peer_risk_profile": handle_compare_peer_risk_profile,
    "compare_peer_accounting_policies": handle_compare_peer_accounting_policies,
    "compare_peer_kam_topics": handle_compare_peer_kam_topics,
    "compare_peer_audit_report_matters": handle_compare_peer_audit_report_matters,
    "search_dataset": handle_search_dataset,
    "fetch_disclosure_on_demand": handle_fetch_disclosure_on_demand,
    "search_audit_report_matters": handle_search_audit_report_matters,
    "search_audit_procedures": handle_search_audit_procedures,
    "compare_peer_audit_procedures": handle_compare_peer_audit_procedures,
    "get_kam_lifecycle": handle_get_kam_lifecycle,
    "get_accounting_policy_changes": handle_get_accounting_policy_changes,
    "get_quality_of_earnings_pack": handle_get_quality_of_earnings_pack,
    "get_dcf_input_candidates": handle_get_dcf_input_candidates,
    "search_disclosure_events": handle_search_disclosure_events,
    "get_audit_report_sections": handle_get_audit_report_sections,
    "estimate_audit_hours_proxy": handle_estimate_audit_hours_proxy,
    "build_audit_acceptance_pack": handle_build_audit_acceptance_pack,
    "get_industry_audit_landscape": handle_get_industry_audit_landscape,
    "build_dcf_model_pack": handle_build_dcf_model_pack,
}
